main:
  name: toy
  end_point:
    url: /home/agobbi/Projects/Incube/forecaster/data/toy.csv
    parameters: {}
  main_folder: /home/agobbi/Projects/Incube/forecaster/data/outputs
  version: 1
  retrain: true

timeseries:
  enrich_cat: ['dow','hour']
  past_variables: ['rain','temp']    
  future_variables: ['rain','temp']

model_configs:
  d_model: 32
  n_head: 4
  hidden_size: 64
  dropout_rate: 0.25
  n_layer_decoder: 2
  use_norm: True
  optim: torch.optim.Adam
  persistence_weight: 0.010
  loss_type: 'l1'
  activation: torch.nn.PReLU
  class_strategy: 'average' #projection/average/cls_token

  past_steps: 168
  future_steps: 48
  quantiles: [0.05,0.5,0.95]

  #leave these null, depends on the dataset
  past_channels: null
  future_channels: null
  embs: null
  out_channels: null

scheduler_config:
  gamma: 0.1
  step_size: 500

optim_config:
  lr: 0.0005
  weight_decay: 0.01

  
split_params:
  perc_train: 0.5
  perc_valid: 0.4
  shift: 0
  skip_step: 1

  #leave null these
  range_train: null
  range_validation: null
  range_test: null
  starting_point: null
  past_steps: null
  future_steps: null

train_config:
  batch_size: 64
  max_epochs: 500
  num_workers: 0
  auto_lr_find: true
  devices: [0]                   
  seed: 42   
  dirpath: null 